name: Tom Smith
age: 37
spouse:
    name: Jane Smith
    age: 25
children:
 - name: Jimmy Smith
   age: 15
 - name1: Jenny Smith
   age1: 12
# 公招全部词条名称
all_staff: 先锋干员 狙击干员 医疗干员 术师干员 近卫干员 重装干员 辅助干员 输出 防护 生存 治疗 费用回复 群攻 支援机械 新手 减速 特种干员 支援 快速复活 削弱 位移 资深干员 召唤 控场 爆发 高级资深干员
# 公招普通词条名称
common_staff: 先锋干员 狙击干员 医疗干员 术师干员 近卫干员 重装干员 辅助干员 输出 防护 生存 治疗 费用回复 群攻 支援机械 新手 减速
# 公招主要词条名称
major_staff: = 特种干员 支援 快速复活 削弱 位移
# 公招资深词条名称
senior_staff: = 资深干员 召唤 控场 爆发
# 公招高级资深词条名称
advanced_senior_staff: 高级资深干员